// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_0Rm1NVS-I7MF8ZcjoEEEoYW64--X-yw',
    appId: '1:374066545933:web:b9bac105a3a5097ae6dc44',
    messagingSenderId: '374066545933',
    projectId: 'zippy-e492a',
    authDomain: 'zippy-e492a.firebaseapp.com',
    storageBucket: 'zippy-e492a.appspot.com',
    measurementId: 'G-GCF1V6FLFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzbSWi67RQ3cy68N4yTmt5NyO7bH9eQlE',
    appId: '1:374066545933:android:c2a4f5e3595e0190e6dc44',
    messagingSenderId: '374066545933',
    projectId: 'zippy-e492a',
    storageBucket: 'zippy-e492a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqq131sJdzuqtgU7Lm8uupBsgk7s1uPpQ',
    appId: '1:374066545933:ios:f2489669b0da2cb4e6dc44',
    messagingSenderId: '374066545933',
    projectId: 'zippy-e492a',
    storageBucket: 'zippy-e492a.appspot.com',
    iosClientId: '374066545933-ummoho26am7gs6g8b5ht4dihlhrr0sb3.apps.googleusercontent.com',
    iosBundleId: 'tech.zippyin.zippy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqq131sJdzuqtgU7Lm8uupBsgk7s1uPpQ',
    appId: '1:374066545933:ios:f2489669b0da2cb4e6dc44',
    messagingSenderId: '374066545933',
    projectId: 'zippy-e492a',
    storageBucket: 'zippy-e492a.appspot.com',
    iosClientId: '374066545933-ummoho26am7gs6g8b5ht4dihlhrr0sb3.apps.googleusercontent.com',
    iosBundleId: 'tech.zippyin.zippy',
  );
}
